# Generated by Django 6.1.1 on 2026-10-05 21:03

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("node_id", models.TextField()),
                ("folder", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("discarded", "Discarded")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("base_digest", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("node_yaml", models.TextField()),
                ("body_md", models.TextField(blank=True)),
                ("exam_yaml", models.TextField(blank=True)),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("change", models.TextField()),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="studio.draft",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="draft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "open")),
                fields=("node_id",),
                name="studio_one_open_draft_per_node",
            ),
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(
                fields=("draft", "number"), name="studio_revision_number"
            ),
        ),
    ]
