# Generated by Django 6.1.1 on 2026-10-06 10:32; the backfill of opened events written by hand
# (M4.5 spec, M4R.5).

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _opened(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Every draft's log starts at its opening, from its revision 1 (M4R.5)."""
    Revision = apps.get_model("studio", "Revision")
    DraftEvent = apps.get_model("studio", "DraftEvent")
    DraftEvent.objects.bulk_create(
        DraftEvent(
            draft_id=first.draft_id,
            kind="opened",
            by_id=first.saved_by_id,
            at=first.saved_at,
            revision=1,
        )
        for first in Revision.objects.filter(number=1)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opened", "Opened"),
                            ("submitted", "Submitted"),
                            ("withdrawn", "Withdrawn"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                            ("sent_back", "Sent Back"),
                            ("discarded", "Discarded"),
                        ],
                        max_length=16,
                    ),
                ),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revision", models.PositiveIntegerField(null=True)),
                ("reason", models.TextField(blank=True)),
                ("self_approved", models.BooleanField(default=False)),
                ("answered", models.PositiveIntegerField(null=True)),
                ("wrong", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("answers", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="draft",
            name="studio_one_open_draft_per_node",
        ),
        migrations.AlterField(
            model_name="draft",
            name="state",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("discarded", "Discarded"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="draft",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["open", "submitted", "approved"])),
                fields=("node_id",),
                name="studio_one_live_draft_per_node",
            ),
        ),
        migrations.AddField(
            model_name="draftevent",
            name="by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftevent",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="studio.draft",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="studio.draft",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftevent",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="studio.review",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("draft", "number", "reviewer"), name="studio_one_review_per_reviewer"
            ),
        ),
        migrations.RunPython(_opened, migrations.RunPython.noop),
    ]
