# Generated by Django 6.1.1 on 2026-10-06 18:35

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0002_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("opened", "Opened"),
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("sent_back", "Sent Back"),
                    ("discarded", "Discarded"),
                    ("landing", "Landing"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("refused", "Refused"),
                            ("open", "Open"),
                            ("failed", "Failed"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("main_head", models.TextField(blank=True)),
                ("branch", models.TextField(blank=True)),
                ("pull_number", models.PositiveIntegerField(blank=True, null=True)),
                ("pull_url", models.TextField(blank=True)),
                ("reason", models.TextField(blank=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("auto_merge", models.BooleanField(default=False)),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="draftevent",
            name="landing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="studio.landing",
            ),
        ),
        migrations.CreateModel(
            name="LandingDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("live", models.BooleanField(default=True)),
                ("dropped_code", models.CharField(blank=True, max_length=6)),
                ("dropped_reason", models.TextField(blank=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="landings",
                        to="studio.draft",
                    ),
                ),
                (
                    "landing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="studio.landing",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("live", True)),
                        fields=("draft",),
                        name="studio_one_live_landing_per_draft",
                    )
                ],
            },
        ),
    ]
