# Generated by Django 6.1.1 on 2026-10-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studio", "0003_landing"),
    ]

    operations = [
        migrations.AddField(
            model_name="landing",
            name="merge_commit",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="draft",
            name="state",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("landed", "Landed"),
                    ("discarded", "Discarded"),
                ],
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="draftevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("opened", "Opened"),
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("sent_back", "Sent Back"),
                    ("discarded", "Discarded"),
                    ("landing", "Landing"),
                    ("landed", "Landed"),
                ],
                max_length=16,
            ),
        ),
    ]
