# Generated by Django 6.1.1 on 2026-09-19 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexBuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outcome",
                    models.TextField(choices=[("applied", "Applied"), ("refused", "Refused")]),
                ),
                ("digest", models.TextField()),
                ("commit", models.TextField(blank=True)),
                ("node_count", models.PositiveIntegerField()),
                ("problems", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("position", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("claim", models.TextField()),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("first-steps", "first-steps"),
                            ("foundations", "foundations"),
                            ("introductory", "introductory"),
                            ("intermediate", "intermediate"),
                            ("advanced", "advanced"),
                        ]
                    ),
                ),
                ("minutes", models.PositiveIntegerField()),
                ("body", models.TextField()),
                ("folder", models.TextField()),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nodes",
                        to="content.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("needs", "Needs"),
                            ("goes-deeper", "Goes Deeper"),
                            ("related", "Related"),
                        ]
                    ),
                ),
                ("reason", models.TextField()),
                ("position", models.PositiveIntegerField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_out",
                        to="content.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_in",
                        to="content.node",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "kind", "target"), name="content_link_once"
                    )
                ],
            },
        ),
    ]
