# Generated by Django 6.1.1 on 2026-09-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("position", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("question_id", models.TextField()),
                ("kind", models.TextField(choices=[("choice", "choice"), ("number", "number")])),
                ("ask", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("answer", models.FloatField(null=True)),
                ("unit", models.TextField(blank=True)),
                ("tolerance", models.FloatField(null=True)),
                ("hints", models.JSONField(default=list)),
                ("rationale", models.TextField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="content.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("video", "video"),
                            ("reading", "reading"),
                            ("tutorial", "tutorial"),
                            ("exercise", "exercise"),
                        ]
                    ),
                ),
                ("url", models.TextField()),
                ("part", models.TextField(blank=True)),
                ("covers", models.TextField()),
                ("licence", models.TextField()),
                ("display", models.TextField(choices=[("embed", "embed"), ("link", "link")])),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("first-steps", "first-steps"),
                            ("foundations", "foundations"),
                            ("introductory", "introductory"),
                            ("intermediate", "intermediate"),
                            ("advanced", "advanced"),
                        ]
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="content.node",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="content.provider",
                    ),
                ),
            ],
        ),
    ]
