# Generated by Django 6.1.1 on 2026-09-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_resources_and_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="video",
            field=models.TextField(blank=True),
        ),
    ]
