# Generated by Django 6.1.1 on 2026-09-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_resource_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="blocks",
            field=models.JSONField(default=list),
        ),
    ]
