# Generated by Django 6.1.1 on 2026-09-29 21:09

import re

from django.db import migrations, models

# The body format before M4.1.2: a `{% try <id> %}` line, outside a fence, placed a question.
# Frozen here so this migration reads old rows the same way whatever code_schema becomes.
_TRY = re.compile(r"^\s*\{%\s*try\s+([a-z0-9-]+)\s*%\}\s*$")
_FENCE = re.compile(r"^\s*(```|~~~)")


def _blocks(body: str) -> list[dict[str, str]]:
    blocks: list[dict[str, str]] = []
    text: list[str] = []
    fence: str | None = None

    def flush() -> None:
        if text:
            blocks.append({"kind": "text", "markdown": "".join(text)})
        text.clear()

    for line in body.splitlines(keepends=True):
        opens = _FENCE.match(line)
        if opens is not None and (fence is None or fence == opens.group(1)):
            fence = opens.group(1) if fence is None else None
        found = None if fence is not None else _TRY.match(line)
        if found is None:
            text.append(line)
        else:
            flush()
            blocks.append({"kind": "try", "question": found.group(1)})
    flush()
    return blocks


def fill_blocks(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Rows indexed before blocks existed get them now, so no page is blank until a rebuild."""
    Node = apps.get_model("content", "Node")
    for node in Node.objects.all():
        node.blocks = _blocks(node.body)
        node.save(update_fields=["blocks"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_resource_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="blocks",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(fill_blocks, migrations.RunPython.noop),
    ]
