# Generated by Django 6.1.1 on 2026-10-05 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_node_blocks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="body",
        ),
    ]
