# Generated by Django 6.1.1 on 2026-10-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_remove_node_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("question_id", models.TextField()),
                ("kind", models.TextField(choices=[("choice", "choice"), ("number", "number")])),
                ("ask", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("answer", models.FloatField(null=True)),
                ("unit", models.TextField(blank=True)),
                ("tolerance", models.FloatField(null=True)),
                (
                    "level",
                    models.TextField(
                        choices=[
                            ("first-steps", "first-steps"),
                            ("foundations", "foundations"),
                            ("introductory", "introductory"),
                            ("intermediate", "intermediate"),
                            ("advanced", "advanced"),
                        ],
                        null=True,
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam",
                        to="content.node",
                    ),
                ),
            ],
        ),
    ]
