# Generated by Django 6.1.1 on 2026-10-05 20:55; the JSON conversions written by hand (M4W.2).

from django.db import migrations, models


def _to_json(table: str, column: str) -> migrations.SeparateDatabaseAndState:
    """A float column becomes JSON, its values kept: Postgres cannot cast double precision to
    jsonb by itself, so `to_jsonb` converts each value. The index is derived data, and the next
    rebuild writes every integer back exactly."""
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunSQL(
                f'ALTER TABLE "{table}" ALTER COLUMN "{column}" TYPE jsonb '
                f'USING to_jsonb("{column}")',
                reverse_sql=(
                    f'ALTER TABLE "{table}" ALTER COLUMN "{column}" TYPE double precision '
                    f'USING ("{column}")::text::double precision'
                ),
            )
        ],
        state_operations=[
            migrations.AlterField(
                model_name=table.removeprefix("content_"),
                name=column,
                field=models.JSONField(null=True),
            )
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_exam_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="embed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="licences",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="provider",
            name="players",
            field=models.JSONField(default=list),
        ),
        _to_json("content_examquestion", "answer"),
        _to_json("content_examquestion", "tolerance"),
        _to_json("content_question", "answer"),
        _to_json("content_question", "tolerance"),
    ]
