# Generated by Django 6.1.1 on 2026-10-05 20:55; the conversions to text written by hand (M4W.2).
# Run rebuild_index after migrating: providers gain their licences, embedding and players, and
# every number is written back as its file has it.

from django.db import migrations, models


def _to_text(table: str, column: str) -> migrations.SeparateDatabaseAndState:
    """A float column becomes text, its values kept (content.numbers, #173). The cast writes
    96.0 as "96", which reads back an int; the index is derived data, and rebuild_index after
    migrating writes every number back exactly as its file has it."""
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunSQL(
                f'ALTER TABLE "{table}" ALTER COLUMN "{column}" TYPE text USING "{column}"::text',
                reverse_sql=(
                    f'ALTER TABLE "{table}" ALTER COLUMN "{column}" TYPE double precision '
                    f'USING "{column}"::double precision'
                ),
            )
        ],
        state_operations=[
            migrations.AlterField(
                model_name=table.removeprefix("content_"),
                name=column,
                field=models.TextField(null=True),
            )
        ],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_exam_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="embed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="licences",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="provider",
            name="players",
            field=models.JSONField(default=list),
        ),
        _to_text("content_examquestion", "answer"),
        _to_text("content_examquestion", "tolerance"),
        _to_text("content_question", "answer"),
        _to_text("content_question", "tolerance"),
    ]
