# Generated by Django 6.1.1 on 2026-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_read_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexbuild",
            name="source",
            field=models.TextField(blank=True),
        ),
    ]
