# Generated by Django 6.1.1 on 2026-10-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_build_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examquestion",
            name="ask",
        ),
        migrations.AddField(
            model_name="examquestion",
            name="accept",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="claim",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="exact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="stem",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="steps",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="question",
            name="accept",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="exact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="steps",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="kind",
            field=models.TextField(
                choices=[
                    ("choice", "choice"),
                    ("number", "number"),
                    ("sequence", "sequence"),
                    ("order", "order"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.TextField(
                choices=[
                    ("choice", "choice"),
                    ("number", "number"),
                    ("sequence", "sequence"),
                    ("order", "order"),
                ]
            ),
        ),
    ]
